export const ROUTER_READY = 'ROUTER_READY';
export const SKIP_WELCOME_SCREENS = 'SKIP_WELCOME_SCREENS';
export const FACEBOOK_CONNECT = 'FACEBOOK_CONNECT';
export const FACEBOOK_LOGIN = 'FACEBOOK_LOGIN';
export const FACEBOOK_CONNECT_IGNORED = 'FACEBOOK_CONNECT_IGNORED';
export const FACEBOOK_CONNECT_FAILED = 'FACEBOOK_CONNECT_FAILED';
export const FACEBOOK_CONNECT_IN_PROGRESS = 'FACEBOOK_CONNECT_IN_PROGRESS';

export const GO_ONLINE = 'GO_ONLINE';
export const GO_OFFLINE = 'GO_OFFLINE';

export const OPEN_ADD_NEW_MODAL = 'OPEN_ADD_NEW_MODAL';
export const CLOSE_ADD_NEW_MODAL = 'CLOSE_ADD_NEW_MODAL';

export const OPEN_PHRASE = 'OPEN_PHRASE';
export const CLOSE_PHRASE_MODAL = 'CLOSE_PHRASE_MODAL';

export const SHOW_RECORDING_PERMISSIONS_MODAL = 'SHOW_RECORDING_PERMISSIONS_MODAL';
export const RECORDING_PERMISSIONS_DENIED = 'RECORDING_PERMISSIONS_DENIED';
export const RECORDING_PERMISSIONS_GRANTED = 'RECORDING_PERMISSIONS_GRANTED';

export const SHOW_SYNC_MODAL = 'SHOW_SYNC_MODAL';
export const HIDE_SYNC_MODAL = 'HIDE_SYNC_MODAL';

export const FORM_ORIGINAL_CHANGED = 'FORM_ORIGINAL_CHANGED';
export const FORM_TRANSLATED_CHANGED = 'FORM_TRANSLATED_CHANGED';
export const FORM_SCROLL_TO_PAGE = 'FORM_SCROLL_TO_PAGE';

export const ADD_NEW_PHRASE = 'ADD_NEW_PHRASE';
export const ADD_SHARED_PHRASE = 'ADD_SHARED_PHRASE';
export const ADD_SHARED_PHRASES = 'ADD_SHARED_PHRASES';
export const ADD_SHARED_DICTIONARY = 'ADD_SHARED_DICTIONARY';
export const UPDATE_PHRASE = 'UPDATE_PHRASE';
export const DELETE_PHRASE = 'DELETE_PHRASE';
export const DELETE_DICTIONARY = 'DELETE_DICTIONARY';
export const CANCEL_SHARE = 'CANCEL_SHARE';
export const SHARE_PHRASE = 'SHARE_PHRASE';
export const SHARE_PHRASE_COMPLETED = 'SHARE_PHRASE_COMPLETED';
export const SHARE_ALL_PHRASES = 'SHARE_ALL_PHRASES';
export const SHARE_ALL_PHRASES_COMPLETED = 'SHARE_ALL_PHRASES_COMPLETED';
export const SHARE_DICTIONARY = 'SHARE_DICTIONARY';
export const SHARE_DICTIONARY_COMPLETED = 'SHARE_DICTIONARY_COMPLETED';
export const DATA_LOADING = 'DATA_LOADING';
export const DATA_LOADED = 'DATA_LOADED';
export const DATA_LOADING_FAILED = 'DATA_LOADING_FAILED';
export const PHRASE_UPLOADED = 'PHRASE_UPLOADED'; // audio uploaded
export const PHRASE_SYNCED = 'PHRASE_SYNCED'; // entire phrase is synced
export const ALL_PHRASES_SYNCED = 'ALL_PHRASES_SYNCED'; // all phrases are now synced, enable sharing
export const PLAY_PHRASE = 'PLAY_PHRASE';
export const PLAY_ALL = 'PLAY_ALL';
export const PLAYBACK_JUST_FINISHED = 'PLAYBACK_JUST_FINISHED';

export const TOGGLE_DICTIONARY_SELECTOR = 'TOGGLE_DICTIONARY_SELECTOR';
export const ADD_DICTIONARY = 'ADD_DICTIONARY';
export const SELECT_DICTIONARY = 'SELECT_DICTIONARY';
export const UPDATE_DICTIONARY_NAME = 'UPDATE_DICTIONARY_NAME';

export const AUDIO_CACHED = 'AUDIO_CACHED';
